# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM ghcr.io/astral-sh/uv:python3.10-bookworm-slim AS uv

WORKDIR /app

COPY pyproject.toml /app/
COPY README.md /app/

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=README.md,target=README.md \
    uv sync --no-dev --no-editable

ADD ./src/mcp_domain_availability /app/mcp_domain_availability

FROM python:3.10-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY --from=uv /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"

COPY --from=uv /app /app/
ENV PYTHONPATH=/app

EXPOSE 8080

ENTRYPOINT ["python", "-m", "mcp_domain_availability.main"]